---
title: "sm_functions"
author: "Samuel Mak"
date: '2022-12-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sm_rowcol  <- 
  function(data, FUN = sum, which_cols = c(), which_rows = c(), digits = c(), where = "both", label = c("Col Result", "Row Result")){
  #Input
  where <- where
  dat <- data
  if(is.null(which_cols)){
    which_cols <- names(dat)
  } 
  if(is.null(which_rows)){
    which_rows <- 1:nrow(dat)
  }
 #cols <- c("Sepal.Length", "Sepal.Width")
  if(!where %in% c("col", "cols", "Col", "Cols","column", "columns", "c", "C", "row", "rows", "Row", "Rows", "r", "R", "both", "Both", 'b', 'B') ){stop("input for the where argument can only be 'col', 'cols', 'Col', 'Cols','column', 'columns', 'c', 'C', 'row', 'rows', 'Row', 'Rows', 'r', 'R', 'both', 'Both', 'b', 'B'")}
  if(length(dat[,duplicated(names(dat))]) > 1){stop("There cannot be duplicates in column names")}

  
  if(length(which_cols) == 1){
  dat_if_cols_length_is_1 <- data.frame(x = dat[, which_cols] )
  names(dat_if_cols_length_is_1) <- which_cols
  dat_2 <- data.frame(x  = dat_if_cols_length_is_1[, unlist(lapply(dat_if_cols_length_is_1, is.numeric), use.names = FALSE)])
  names(dat_2) <- which_cols
  } else if(length(which_cols) != 1){
    dat_2 <- dat[, which_cols][, unlist(lapply(dat[, which_cols], is.numeric), use.names = FALSE)]
  }
  

  #Check if the columns/rows are numeric otherwise delete them and notify the user that that col is not numeric and is deleted
  
  #Warning message
  cols_not_numeric <- names(dat[, which_cols][!names(dat[, which_cols]) %in% names(dat_2)])
  col_not_numeric_warning_head <- 
    if(length(cols_not_numeric) == 1){"WARNING: The following column is not numeric and is ignored"} else if(length(cols_not_numeric) > 1){"The following columns are not numeric and are ignored"}
  cols_not_numeric_df <- cols_not_numeric |> as.data.frame()
  names(cols_not_numeric_df) <- col_not_numeric_warning_head
  
  
  #Col function
  col_function <- function(original_dat, adjusted_dat, label, FUN){
    #adjusted_dat <- dat_2
    #original_dat <- iris
   
    results_df <- data.frame(col = c(), result = c())
    # Col name

    for(i in if(length(adjusted_dat) == 1){1} else if(length(adjusted_dat) != 1){1:length(adjusted_dat)}){
      results_df[i, 1] <- names(adjusted_dat)[i]
      results_df[i, 2] <- FUN(adjusted_dat[[i]])
      }
    
    results_df_2 <- data.frame(t(results_df))
    
    if(length(which_cols) == 1){
      results_df_2 <- data.frame(as.numeric(results_df_2[-1, ]))
      names(results_df_2) <- which_cols
    } else if(length(which_cols) != 1){
      names(results_df_2) <- results_df_2[1,]
      results_df_2 <- results_df_2[-1, ]
      results_df_2 <- data.frame(lapply(results_df_2, as.numeric))
    }
    
    
    #Add a column in if the first column is numeric 
    if(is.numeric(original_dat[,1])){
      total_col <- data.frame(total_col = rep("", nrow(original_dat)))
      original_dat <- cbind(total_col, original_dat)
      names(original_dat)[1] <- label[1]
    } 
    
    #Adjustig the label
    original_dat[nrow(original_dat) + 1, 1]  <- label[1]
    
    #Adding the results to the orignal dataframe
    for(i in if(length(adjusted_dat) == 1){1} else if(length(adjusted_dat) != 1){1:length(adjusted_dat)}){
      original_dat[nrow(original_dat) , which(names(original_dat) == names(results_df_2)[i])] <- if(is.null(digits)){results_df_2[[i]]} else
        if(!is.null(digits)){round(results_df_2[[i]], digits = digits)}
      }
    return(original_dat)
  }

  # Row function
  row_function <- function(original_dat, adjusted_dat, label, FUN){
  
    #original_dat <- final_df
    #adjusted_dat <- dat_2
    adjusted_dat <- data.frame(t(adjusted_dat))
    results_df <- data.frame(row_result = unlist(lapply(adjusted_dat, FUN = FUN)))
    results_vector <- unlist(lapply(adjusted_dat, FUN = FUN))
    logic <- 1:length(results_vector) %in% which_rows
    results_vector[which(logic == "FALSE")] <- NA
    results_df <- data.frame(row_result = results_vector)
    if(where %in% c("both", "Both", "B", "b")){results_df[nrow(results_df) + 1,] <- NA}
    
    #Adding the result to the orignal dataframe and adjusting the label name
    original_dat[,length(original_dat)+1] <- results_df
    names(original_dat)[length(original_dat)]  <- label
    return(original_dat)
    }

  if(where %in% c("col", "cols", "Col", "Cols","column", "columns", "c", "C")){
    final_df <- col_function(original_dat = dat, adjusted_dat = dat_2, label = label[1], FUN = FUN)
    } else
  if(where %in% c("row", "rows", "Row", "Rows", "r", "R")){
    final_df <- row_function(original_dat = dat, adjusted_dat = dat_2, label = label[2], FUN = FUN)
    } else
  if(where %in% c("Both", "both", "b", "B")){
    final_df <- col_function(original_dat = dat, adjusted_dat = dat_2, FUN = FUN, label = label[1])
    final_df <- row_function(original_dat = final_df, adjusted_dat = dat_2, FUN = FUN, label = label[2])                     
    }
  output <- list(cols_not_numeric_df, output = final_df)
  return(output)
}

```




```{r pressure, echo=FALSE}


gias_mat <- function(uid){
  
#Check package 
if(length(setdiff(c("tidyverse", "rvest"), rownames(installed.packages())) ) > 0){
  install.packages(c("tidyverse", "rvest"))
}


output_df <- 
  data.frame(
    mat = c(),
    mat_uid = c(),
    academy_name = c(),
    address = c(),
    phase_type = c(),
    urn = c(),
    ukprn = c(),
    laestab = c(),
    la = c(),
    status = c(),
    joined_date_as_character = c()
    ) 
  
for(i in 1:length(uid)){

  html <- rvest::read_html(paste0("https://www.get-information-schools.service.gov.uk/Groups/Group/Details/", uid[i],"#list")) 
  
  mat_name <- 
    html |> 
    rvest::html_elements("span") |> 
    rvest::html_nodes(xpath = '//*[@id="establishment-group-name"]')  |> 
    rvest::html_text2()
  
  mat_uid <- 
    html |> 
    rvest::html_elements("span") |> 
    rvest::html_nodes(xpath = '//*[@id="uid-value"]')  |> 
    rvest::html_text2()

  academy_list <- 
    html |> 
    rvest::html_nodes("ul.school-results-listing") |> 
    rvest::html_elements("li") 

  academy_name <- academy_list |> rvest::html_elements("h2") |> rvest::html_text2()

  academy_list_dl <- academy_list |> rvest::html_elements("dl")
  
  status <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-status-value"]')  |> rvest::html_text2() 
  
  joined_date <- academy_list_dl |> rvest::html_nodes(xpath = '//*[@id="establishment-joined-date-value"]')  |> rvest::html_text2()
  
  urn <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-urn-value"]')  |> rvest::html_text2()
  
  address <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-address-value"]')  |> rvest::html_text2()
  
  phase_type <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-phase-type-value"]')  |> rvest::html_text2()
  
  ukprn <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-ukprn-value"]')  |> rvest::html_text2()
  
  laestab <- academy_list_dl  |> rvest::html_nodes(xpath = '//*[@id="establishment-laestab-value"]')  |> rvest::html_text2()
  
  la <- academy_list_dl |> rvest::html_nodes(xpath = '//*[@id="establishment-la-value"]')  |> rvest::html_text2()

  object_list <-  list(
    mat_name = mat_name,
    mat_uid = mat_uid,
    academy_name = academy_name,
    address = address,
    phase_type = phase_type,
    urn = urn,
    ukprn = ukprn, 
    laestab = laestab, 
    la = la,
    status = status, 
    joined_date_as_character = joined_date
    )
  
  for(k in 1:length(object_list)){
  #k <- 1
    if(length(object_list[[k]]) == 0){
      object_list[[k]] <- NA
    }
  }
 

  looping_df <- 
    data.frame(
      mat = object_list$mat_name,
      mat_uid = object_list$mat_uid,
      academy_name = object_list$academy_name,
      address = object_list$address,
      phase_type = object_list$phase_type,
      urn = object_list$urn,
      ukprn = object_list$ukprn, 
      laestab = object_list$laestab, 
      la = object_list$la,
      status = object_list$status, 
      joined_date_as_character = object_list$joined_date
      ) 

  output_df <- rbind(output_df, looping_df)

}

output_df <- 
  output_df |> 
  dplyr::mutate(
    academy_name = trimws(gsub("\r", "", academy_name)),
    phase_type = trimws(gsub("\r", "", phase_type)),
    phase = trimws(gsub(",.*", "", phase_type)),
    type = trimws(gsub(".*,", "", phase_type)),
    joined_date_as_date = as.Date(joined_date_as_character, tryFormats = "%d %B %Y")
  )  |> 
  dplyr::select(mat, mat_uid, academy_name, address, phase, type, urn, ukprn, laestab, status, la, joined_date_as_character, joined_date_as_date)

return(output_df)

}

gias_mat(uid = c(3320, 4474,4320, 1383, 5547, 	2748, 2894))
s <- Sys.time()
gias_mat(uid = 4474)
e <- Sys.time()
e-s
c(
7.094354,
11.2063 ,
16.30495,
22.13463,
 27.75341,
 32.41989, 
38.09229,
42.35471,
47.03511,53.18831, 58.6897, 60.095808)

#12 DELTA per minute
```
```{r}

  system.file(package = "adimpro")

package_path <- find.package(package = c("tidyverse", "adimpro"), quiet = T)


rownames(installed.packages())
c("tidyverse", "adimpro", "betaclust")





```

```{r}
start_1 <- Sys.time()
install.packages(setdiff(c("tidyverse", "rvest"), rownames(installed.packages())))
end_1 <-Sys.time()

end_1 - start_1

1.280232
0.8182609
0.8138931
0.849122
0.785744
0.847754

start_2 <- Sys.time()
if(length(setdiff(c("tidyverse", "rvest"), rownames(installed.packages())) ) > 0){
  install.packages(c("tidyverse", "rvest"))
}
end_2 <-Sys.time()

end_2 - start_2

0.01677084
0.01274705
0.01450396
0.01343679
0.01346302
```


```{r}
#estimating function running time 


reach2_list <- list()

for(i in 1:30){
reach2_list[[i]] <- rep(4474, i)
}


bristol_list <- list()

for(i in 1:16){
bristol_list[[i]] <- rep(2894, i)
}


reach2_list
bristol_list

t <- c()
for(k in 1:length(reach2_list)){

  start <- Sys.time()
  gias_mat(reach2_list[[k]])
  end <- Sys.time()
  
  t <- c(t, end - start)
}

t_2 <- c()
for(k in 1:length(bristol_list)){

  start_2 <- Sys.time()
  gias_mat(bristol_list[[k]])
  end_2 <- Sys.time()
  
  t_2 <- c(t, end - start)
}

t
t_2

data.frame(
  time = c(t, t_2[1:16]),
  mat_size = rep(c("big", "small"), each = 16),
  n_mats = rep(c(1:16), 2)
) |> 
  ggplot() +
  geom_line(
    mapping = aes(
      x = n_mats,
      y = time,
      colour = mat_size
    )
  )
rep(c("big", "small"), each = 16) |> length()

t |> plot()
```











